apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  PORT: "8080"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "ecommerce"
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_DB: "ecommerce"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB: "ecommerce"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "root"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
